# Generated by Django 4.1.3 on 2024-09-29 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrecadador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(default='00000-000', max_length=8)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Arrecadador',
                'verbose_name_plural': 'Arrecadadores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'tamanho',
                'verbose_name_plural': 'tamanhos',
            },
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('roupa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vestuario',
                'verbose_name_plural': 'vestuarios',
            },
        ),
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('arrecadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacoes', to='example.arrecadador')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='example.genero')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='example.tamanho')),
                ('vestuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacoes', to='example.vestuario')),
            ],
            options={
                'verbose_name': 'Arrecadação',
                'verbose_name_plural': 'Arrecadações',
            },
        ),
    ]
