# Generated by Django 4.1.3 on 2024-10-16 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eletrodosmesticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('eletro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Eletrodomestico',
                'verbose_name_plural': 'Eletrodomestico',
            },
        ),
        migrations.AlterModelOptions(
            name='vestuario',
            options={'verbose_name': 'Vestuario', 'verbose_name_plural': 'Vestuarios'},
        ),
        migrations.CreateModel(
            name='Arrecadacao_eletrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('eletrodomestico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eletrodomesticos', to='example.vestuario')),
            ],
            options={
                'verbose_name': 'Arrecadação_eletrodomestico',
                'verbose_name_plural': 'Arrecadações_eletrodomesticos',
            },
        ),
    ]
