# Generated by Django 4.1.3 on 2024-10-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_eletrodosmesticos_alter_vestuario_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eletrodosmesticos',
            new_name='Eletrodosmestico',
        ),
        migrations.AlterModelOptions(
            name='eletrodosmestico',
            options={'verbose_name': 'Eletrodomestico', 'verbose_name_plural': 'Eletrodomesticos'},
        ),
    ]
