# Generated by Django 4.1.3 on 2024-10-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_arrecadacao_eletrodomestico_eletrodomestico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao_eletrodomestico',
            name='eletrodomestico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eletrodomestico', to='example.eletrodomestico'),
        ),
    ]
