# Generated by Django 4.1.3 on 2024-10-31 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_alter_arrecadacao_eletrodomestico_eletrodomestico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
        migrations.CreateModel(
            name='Arrecadacao_alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacao_alimento', to='example.alimento')),
            ],
            options={
                'verbose_name': 'Arrecadação Alimento',
                'verbose_name_plural': 'Arrecadações Alimentos',
            },
        ),
    ]
