# Generated by Django 4.1.3 on 2024-10-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_alimento_arrecadacao_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='alimento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
