# Generated by Django 4.1.3 on 2024-10-31 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_alter_arrecadacao_alimento_alimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacao_alimento', to='example.alimento'),
        ),
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='criacao',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='arrecadacao_alimento',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
