# Generated by Django 4.1.3 on 2024-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_alter_arrecadacao_alimento_alimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
