# Generated by Django 4.1.3 on 2024-11-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_alter_alimento_criacao_alter_alimento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='criacao',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
