# Generated by Django 4.1.3 on 2024-11-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0014_alter_alimento_criacao_alter_arrecadacao_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrecadacao',
            name='arrecadador',
        ),
    ]
